
title: "MImPG"
description: "Metropolitan Internet meets Post Growth"

show_downloads: false
show_repo: false
google_analytics:

author:
  name: Jan Tobias Muehlberg


# Dinky Theme: https://github.com/pages-themes/dinky
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

