
title: "MImPG: Metropolitan Internet meets Post Growth"
description: "Innoviris Research Platforms 2024: Towards Sustainable Digitalization"

show_downloads: false
google_analytics:

author:
  name: Jan Tobias Muehlberg


# Dinky Theme: https://github.com/pages-themes/dinky
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

